/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AContract } from "./AContract";
export type { BContract } from "./BContract";
export type { IContractA } from "./IContractA";
